### ISSUE TITLE
Auto-update Dependencies

### ISSUE THREAD

**Issue by joypoddar** [CreoWis/next-js-launchpad#4]
Write GitHub Actions to auto-update dependencies

**Comment by Jayakumar03** [comment]
I would like work on this issue.

**Comment by Jayakumar03** [comment]
Hello @atapas,
I hope you are doing good.

**I have some doubts regarding the cron and node version.Here's the relevant code ** 
1. Currently i have scheduled ci  to run at every day using `cron`, Is it ok ?
2. Node vesrion is 14,  is it ok or shall chnage it lasted lts version ?

Yaml for auto update dependices
```
name: Update Dependencies

on:
 schedule:
    - cron: '0 0 * * *' # This runs the workflow daily at midnight

jobs:
 update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14' 

    - name: Install dependencies
      run: npm ci 

    - name: Check for updates
      run: |
        npm outdated --json > outdated.json
        if [ -s outdated.json ]; then
          echo "Updates found"
          echo "::set-output name=updates_found::true"
        else
          echo "No updates found"
          echo "::set-output name=updates_found::false"
        fi
      id: check

    - name: Create Pull Request
      if: steps.check.outputs.updates_found == 'true'
      uses: peter-evans/create-pull-request@v3
      with:
        title: "Update dependencies"
        body: "This PR updates the dependencies to their latest versions."
        branch: "update-dependencies"
        delete-branch: true
        commit-message: "Update dependencies"
        labels: "dependencies"
```


With warn regards
Jayakumar
